spring.application.name=Spotiflie
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=email,profile

spotify.client.id=4abdd1b6743c49429f471b05995bedb0
spotify.client.secret=d7bc0802753c460d812051472fb5825a
spotify.redirect.uri=https://starter-boil-dropbox.ngrok-free.dev/callback
server.forward-headers-strategy=framework
spring.security.oauth2.client.registration.spotify.client-id=4abdd1b6743c49429f471b05995bedb0
spring.security.oauth2.client.registration.spotify.client-secret=d7bc0802753c460d812051472fb5825a
spring.security.oauth2.client.registration.spotify.scope=user-read-email,user-read-private,user-top-read,user-read-recently-played,user-modify-playback-state,user-read-playback-state,streaming
spring.security.oauth2.client.registration.spotify.redirect-uri=https://starter-boil-dropbox.ngrok-free.dev/callback
spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.spotify.authorization-uri=https://accounts.spotify.com/authorize
spring.security.oauth2.client.provider.spotify.token-uri=https://accounts.spotify.com/api/token
spring.security.oauth2.client.provider.spotify.user-info-uri=https://api.spotify.com/v1/me
spring.security.oauth2.client.provider.spotify.user-name-attribute=id